image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  CACHE_ON: "false"
#  GIT_STRATEGY: clone
#  REGISTRY: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  REGISTRY: server-gitlab-runner:5000
  RELEASE: latest
  LOCAL_BUILD: "false"
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build-one
  - build-two
  - build-three
  - build-four

services: # Note the hardcoded registry name...
  - name: docker:dind
    command: ["--insecure-registry=server-gitlab-runner:5000"]

before_script:
  - apk update && apk add bash
  - docker info

# Test if the registry is up and running
test:
  stage: test
  tags:
    - dls2
  script:
  - docker pull alpine
  - docker tag alpine $REGISTRY/alpine:latest
  - docker push $REGISTRY/alpine:latest
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /[skip test]/

build-env:
  stage: build-one
  script:
    - ./build_docker.sh dls2-env $CACHE_ON $RELEASE $LOCAL_BUILD
    - ./push_docker.sh dls2-env $REGISTRY $RELEASE
  tags:
    - dls2
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /[skip one]/   

build-dev:
  stage: build-two
  script:
    - ./build_docker.sh dls2-dev $CACHE_ON $RELEASE $LOCAL_BUILD
    - ./push_docker.sh dls2-dev $REGISTRY $RELEASE
  tags:
    - dls2
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /[skip two]/    

build-framework-dev:
  stage: build-three
  script:
    - ./build_docker.sh dls2-framework-dev $CACHE_ON $RELEASE $LOCAL_BUILD
    - ./push_docker.sh dls2-framework-dev $REGISTRY $RELEASE
  tags:
    - dls2
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /[skip three]/    

build-plugin-dev:
  stage: build-three
  script:
    - ./build_docker.sh dls2-plugin-dev $CACHE_ON $RELEASE $LOCAL_BUILD
    - ./push_docker.sh dls2-plugin-dev $REGISTRY $RELEASE
  tags:
    - dls2
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /[skip three]/    

build-hal-dev:
  stage: build-three
  script:
    - echo "Skipping build"
  tags:
    - dls2
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /[skip three]/    

build-operator:
  stage: build-four
  script:
    - ./build_docker.sh dls2-operator $CACHE_ON $RELEASE $LOCAL_BUILD
    - ./push_docker.sh dls2-operator $REGISTRY $RELEASE
  tags:
    - dls2
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /[skip four]/   

#build-xenomai:
#  stage: build-two
#  script:
#  - ./build_docker.sh dls2-xenomai $CACHE_ON $RELEASE $LOCAL_BUILD
#  - ./push_docker.sh dls2-xenomai $REGISTRY $RELEASE
#  tags:
#    - dls2
