image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  CACHE_ON: "false"
#  GIT_STRATEGY: clone
#  REGISTRY: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  REGISTRY: server-gitlab-runner:5000 #server-dev
  RELEASE: latest #default variable
  LOCAL_BUILD: "false"
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build-start

services: # Note the hardcoded registry name...
  - name: docker:dind
    command: ["--insecure-registry=server-gitlab-runner:5000"]

before_script:
  - apk update && apk add bash
  - docker info

# Test if the registry is up and running
test:
  stage: test
  tags:
    - dls2
  script:
  - docker pull alpine
  - docker tag alpine $REGISTRY/alpine:latest
  - docker push $REGISTRY/alpine:latest

build-env:
  stage: build-start
  script:
  - ./build_docker.sh dls2-env $CACHE_ON $RELEASE $LOCAL_BUILD
  - ./push_docker.sh dls2-env $REGISTRY $RELEASE


